spring:
   main:
    allow-bean-definition-overriding: true
   datasource: 
           url: jdbc:h2:mem:camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
           driver-class-name: org.h2.Driver
           username: sa
           password: sa
   h2:
    console:
      enabled: true
      path: /h2-console

camunda.bpm.admin-user:
  id: demo
  password: demo

server:
   port: 8086

csv:
  file:
    path: classpath:LoanIQActJobs.csv